name: build and push latest image
# https://github.com/marketplace/actions/docker-buildx

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch version information
        id: buildargs
        run: |
          VERSION=`echo '${{ github.sha }}' | cut -c1-7`
          IMAGE_TAG=latest

          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
            VERSION=${IMAGE_TAG}-${VERSION}
          fi

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tag::${IMAGE_TAG}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: pg2es/search-replica:${{ steps.buildargs.outputs.tag }}
          build-args: |
            VERSION=${{ steps.buildargs.outputs.version }}
